import type { ColorPalette } from "@chakra-ui/react";

/**
 * Semantic status intents Badge and Tag both support, sharing one mapping
 * to an AERYO colorPalette token family (mirrors
 * `actions/internal/intentColorPalette.ts`'s reasoning) — consumers
 * reason in intents ("error"), never in colors ("colorPalette=danger").
 *
 * Named `neutral`/`success`/`warning`/`error`/`info` (not
 * `primary`/`secondary`/`danger` like Button's `ButtonIntent`) because
 * these are status indicators, not action intents — the spec's own
 * vocabulary for Badge/Tag. `error` maps to the same `danger` family
 * Button's `danger` intent uses; `info` maps to `teal` (AERYO's one
 * brand color) since no dedicated "info" family exists — reusing the
 * brand color for informational status, not as a second decorative
 * accent, doesn't conflict with the restraint principle (semantic-tokens
 * .ts): it's still one primary, just applied to a status use rather than
 * an action.
 *
 * `ColorPalette` (from `@chakra-ui/react`) is generated by
 * `@chakra-ui/cli`'s `chakra typegen` against this project's actual
 * theme (see the `postinstall` script in package.json) — these AERYO
 * families are real, typed members of it, same as
 * `actions/internal/intentColorPalette.ts`.
 */
export type StatusIntent = "neutral" | "success" | "warning" | "error" | "info";

/**
 * Visual treatments shared by Badge and Tag — Chakra's own recipe variant
 * names for both (Tag's slot recipe literally reuses Badge's `variant`
 * definitions). `plain` is intentionally out of scope, matching Button's
 * variant subset.
 */
export type StatusVariant = "solid" | "subtle" | "outline" | "surface";

export const STATUS_COLOR_PALETTE: Record<StatusIntent, ColorPalette> = {
  neutral: "ink",
  success: "success",
  warning: "caution",
  error: "danger",
  info: "teal",
};
