import type { ColorPalette } from "@chakra-ui/react";
import type { ButtonIntent } from "../Button/Button.types";

/**
 * Maps each AERYO semantic intent to the Chakra colorPalette that renders
 * it, shared by every actions/ component that exposes an `intent` prop
 * (Button, IconButton, …), so the mapping — and its one-time fix — lives
 * in exactly one place.
 *
 * `ink`/`success`/`caution`/`danger` are AERYO's own color families
 * (src/design-system/tokens/colors.ts) with full 50-950 scales and their
 * own colorPalette semantic-token blocks (src/design-system/theme/
 * semantic-tokens.ts), added there for the same reason Chakra ships one
 * for every default family (gray, red, teal, …): without it,
 * `colorPalette="ink"` silently renders as an unstyled native button.
 * `teal` is Chakra's own default palette name, reclaimed by AERYO and
 * partially overridden in the same file so `solid`/`contrast` reuse the
 * WCAG-verified `accent.*` tokens instead of Chakra's stock formula.
 *
 * `ColorPalette` (from `@chakra-ui/react`) is generated by
 * `@chakra-ui/cli`'s `chakra typegen` against this project's actual theme
 * (see the `postinstall` script in package.json, which reruns it on
 * every install — the output lives in node_modules, so it doesn't
 * survive a fresh install on its own) — these AERYO families are real,
 * typed members of it, not a cast-your-way-past-it workaround.
 */
export const INTENT_COLOR_PALETTE: Record<ButtonIntent, ColorPalette> = {
  primary: "teal",
  secondary: "ink",
  success: "success",
  warning: "caution",
  danger: "danger",
};
